import type { Metadata } from "next";
import "./globals.css";
import Header from "@/component/Header";
import Footer from "@/component/Footer";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="flex flex-col">
      <Header />
      <body id="header"
      >
        {children}
      </body>
      <Footer />
    </html>
  );
}
